// <auto-generated />
namespace RentKrok.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBWork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBWork));
        
        string IMigrationMetadata.Id
        {
            get { return "201912122003416_DBWork"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
